FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY  --from=build /app/dist /app

RUN npm install -g serve

CMD ["serve", "-s", ".","-l", "3000"]


